In [ ]:
----------------Data Analysis----------------------------
1.Pandas    -------    Datframe read and write opeartions
2.Numpy     -------    Numeriacl Python Math operations
3.matplotlib -----     plots , Graphs, Visulization
4.Seaborn    -----     plots
5.plotly     ----      plots
6.Bokhe      ----       plots

--------------- Machine learning ------------------------
7. Sickit-learn (sklearn) ===== Model development
8. stats packages         ===== Linear regression

================ Webscrapping and Database connection ========
9. Sqlite           ======== SQL connection
10. Beautiful soup  ======= scarp the data 
11. websocket       ======= Scrap the data 

================== Deep learning =======================
12. Tensorflow     ==== deep learning models development(google)
13. keras 
14. pytorch       ===== develop by facebook(meta)
15. Opencv        ===== computer vision(reading and writing images)
16. Pillow        ==== reading images
================== NLP =================================
17. NLTK        ===== Natural language tool kit
18. SpaCy       ====  NLP models
19. wordcloud   ====  
================= Web development -API ========================
20. Flask
21. Django
22. Fast API
23. Gradio
================ Apps creation ================================
24. Streamlit
================== Transformers BERT ================
25. Transformers ==== Huggingface (Google)
==================== DL:Pretrained Models Object Detections =================
26. Vgg16
27. Mobilenet
28. Yolo ----- Ultralytics
===================== NLP pretrained Models ==================
29.Word2Vec ----- Google
30.GloVe   ----- StandforUniversity

=================== Model save =======================
31. Pickle  
32. Joblib

=================== GenAI LLM ====================
33. Azure openAI 
34. Google Gemini
35. Amazon BedRock
36. LLAMA Meta AI
37. Langchain Framework
===================== Model Deployment =============
38. Mlflow

====================== Cloud services ==============
39. Azure Ml related packages
40. GCP vertex ai packages
41. Amazon sagemaker packages

================= Alle NLP =======================
42. Allen NLP packages

===================== ML using Pyspark ===========
43. MLlib package
================= Small packages =================
44. random
45. math
46. time
47. logger 



**Step-1: Import packages**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2:Create a DataFrame using List**

In [2]:
import pandas as pd
data=pd.DataFrame()
# we create a DataFrame
# But no data(No rows and No columns)
# We saved our dataframe with a name 'data'
data

Empty DataFrame
Columns: []
Index: []

**Step-3: Provide the data**

In [3]:
name=['Raj','Abhi','Chinna']
pd.DataFrame(name)

0
0     Raj
1    Abhi
2  Chinna

In [4]:
name=['Raj','Abhi','Chinna']
age =[20,21,22]
pd.DataFrame(zip(name,age)) 

0   1
0     Raj  20
1    Abhi  21
2  Chinna  22

In [5]:
name=['Raj','Abhi','Chinna']
age =[20,21,22]
city =['Pune','Hyd','Delhi']
pd.DataFrame(zip(name,age,city))

0   1      2
0     Raj  20   Pune
1    Abhi  21    Hyd
2  Chinna  22  Delhi

In [6]:
name=['Raj','Abhi','Chinna']
age =[20,21,22]
city =['Pune','Hyd','Delhi']
data=[name,age,city]
pd.DataFrame(data)

0     1       2
0   Raj  Abhi  Chinna
1    20    21      22
2  Pune   Hyd   Delhi

In [7]:
name=['Raj','Abhi','Chinna']
age =[20,21,22]
city =['Pune','Hyd','Delhi']
df=pd.DataFrame(zip(name,age,city))
df

0   1      2
0     Raj  20   Pune
1    Abhi  21    Hyd
2  Chinna  22  Delhi

**Ste-4:Provide the columns**

- Columns we need to provide in a list

- The number of columns exactly match with data 

- Here we have 3 columns , so we need to create a list with 3 names

In [8]:
name=['Raj','Abhi','Chinna']
age =[20,21,22]
city =['Pune','Hyd','Delhi']
cols=['Names','Age','City']
df=pd.DataFrame( zip(name,age,city),
                 columns=cols
               )
df

Names  Age   City
0     Raj   20   Pune
1    Abhi   21    Hyd
2  Chinna   22  Delhi

**Ste-5:Provide the index**

In [9]:
name=['Raj','Abhi','Chinna']
age =[20,21,22]
city =['Pune','Hyd','Delhi']
cols=['Names','Age','City']
id=['A','B','C']
df=pd.DataFrame( zip(name,age,city),
                index=id,
                 columns=cols
               )
df

Names  Age   City
A     Raj   20   Pune
B    Abhi   21    Hyd
C  Chinna   22  Delhi

**Step-6: How to add a New column to already Existed dataframe**

- here we alreday has a dataframe with name **df**

- It has 3 columns

- Now we want add a new column **Marks**

- We need to create a new array or list 

- That length of list should equal to len of rows

- so here we have 3 rows, so new list also has 3 values

In [10]:
# df['<new column name>']=<list>
marks=[100,200,300]
df['Marks']=marks
df

Names  Age   City  Marks
A     Raj   20   Pune    100
B    Abhi   21    Hyd    200
C  Chinna   22  Delhi    300

**Step-7:Create a Dataframe using an empty dataframe**

- In above case we created a list

- we create a dataframe by passing the list 

In [ ]:
# name=['Raj','Abhi','Chinna']
# age =[20,21,22]
# city =['Pune','Hyd','Delhi']
# cols=['Names','Age','City']
# id=['A','B','C']
# df=pd.DataFrame( zip(name,age,city),
#                 index=id,
#                  columns=cols
#                )
# df

In [11]:
# dataframe is created
df1=pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [14]:
name=['Raj','Abhi','Chinna']
age =[20,21,22]
city =['Pune','Hyd','Delhi']
df1['Name']=name
df1['Age']=age
df1['City']=city
df1

Name  Age   City
0     Raj   20   Pune
1    Abhi   21    Hyd
2  Chinna   22  Delhi

**Step-8: Create a Dataframe using Dictionary**

In [15]:
dict1={'Name':['Raj','Abhi','Chinna'],
      'Age':[20,21,22],
      'City':['Pune','Hyd','Delhi']}
dict1

{'Name': ['Raj', 'Abhi', 'Chinna'],
 'Age': [20, 21, 22],
 'City': ['Pune', 'Hyd', 'Delhi']}

In [18]:
df2=pd.DataFrame(dict1,index=['A','B','C'])
df2

Name  Age   City
A     Raj   20   Pune
B    Abhi   21    Hyd
C  Chinna   22  Delhi

- keys behave as columns

- values behave as rows 

In [26]:
dict1={'Names':'Raj',
      'Age':20,
      'City':'Hyd'}
pd.DataFrame(dict1,index=[1])
# If using all scalar values, you must pass an index

Names  Age City
1   Raj   20  Hyd
2   Raj   20  Hyd

- Data in the form array

    - list : Normal way

    - numpy : Numpy package

    - tensor : Tensorflow

In [27]:
l1=[1,2,3]
import numpy as np
np.array(l1)

# tensor([1,2,3])

array([1, 2, 3])

In [28]:
l1=[1,2,3]
l2=[11,12,13]
l1+l2

[1, 2, 3, 11, 12, 13]

In [31]:
l1=[1,2,3]
a=np.array(l1)
l2=[11,12,13]
b=np.array(l2)
a+b,a*b

(array([12, 14, 16]), array([11, 24, 39]))

**Step-9:Drop the Column**

- in order to drop a column we need to use **drop** method

- All the methods based on your dataframe name similar as string names

- It requires mainly 3 arguments

    - 1. Column name 

    - 2. axis 

        - axis=1  represents column

        - axis=0  represents rows

   - 3. inplace 

        - once you drop the column , the dataframe affected

        - the modified dataframe wants to save in a same name or different name

        - if you want to keep at same name then **inplace=True**

        

In [34]:
#Create a data frame drop any column
name=['Raj','Abhi','Chinna']
age =[20,21,22]
city =['Pune','Hyd','Delhi']
cols=['Names','Age','City']
id=['A','B','C']
df=pd.DataFrame(zip(name,age,city),index=id,columns=cols)
df.drop('City',axis=1,inplace=True)
df

Names  Age
A     Raj   20
B    Abhi   21
C  Chinna   22

In [37]:
name=['Raj','Abhi','Chinna']
age =[20,21,22]
city =['Pune','Hyd','Delhi']
cols=['Names','Age','City']
id=['A','B','C']
df=pd.DataFrame(zip(name,age,city),index=id,columns=cols)
df.drop('A',axis=0,inplace=True)
df

Names  Age   City
B    Abhi   21    Hyd
C  Chinna   22  Delhi

In [ ]:
# Create two dataframes df1 and df2
# add those dataframes
########## df1 ########
Names   Age  City
Ramesh  20   Hyd

###### df2 ###########
Names  Age  City
Suresh  21   Blr

Names  Age  City
Ramesh  20   Hyd
Suresh  21   Blr


append
concat
join

**Step-10: How to overwrite existed column data**

- We already has a dataframe

- Now we want replace all the values of a specific column with new values

- First create a list with new values

- Then update the column with new values, in the same way of how to create a new column

- df[new col]=data , to create a new column

- df[old col]= new data , to overwrite the old column

In [40]:
df['Age']=[31,33]

In [41]:
df

Names  Age   City
B    Abhi   31    Hyd
C  Chinna   33  Delhi

**Step-11:How to Save the Dataframe**

- we can save the dataframe using 2 ways

- csv : comma seperated value

- excel

- For csv : .to_csv   extention=.csv

- For excel: .to_excel  extention=.xlsx

In [42]:
# Create a Dataframe
name=['Raj','Abhi','Chinna']
age =[20,21,22]
city =['Pune','Hyd','Delhi']
cols=['Names','Age','City']
id=['A','B','C']
df=pd.DataFrame(zip(name,age,city),index=id,columns=cols)
df

Names  Age   City
A     Raj   20   Pune
B    Abhi   21    Hyd
C  Chinna   22  Delhi

**Csv format**

In [43]:
# Dataframename.methodname
# where you want to save
# in what name you want to save
df.to_csv('data.csv')

**Excel sheet**

In [44]:
df.to_excel('data1.xlsx')

**Step-12 : Read the data**

- read_csv

- read_excel

- both availabel on pandas

In [45]:
pd.read_csv('data.csv')

Unnamed: 0   Names  Age   City
0          A     Raj   20   Pune
1          B    Abhi   21    Hyd
2          C  Chinna   22  Delhi

In [47]:
pd.read_excel('data1.xlsx')

Unnamed: 0   Names  Age   City
0          A     Raj   20   Pune
1          B    Abhi   21    Hyd
2          C  Chinna   22  Delhi

**Step-13: How to avoid extra column**

- while we are saving the data, we have argument name **index**

- keep index=False

In [48]:
# Give the differnt name, provide index= False
df.to_csv('data11.csv',index=False)
pd.read_csv('data11.csv')

Names  Age   City
0     Raj   20   Pune
1    Abhi   21    Hyd
2  Chinna   22  Delhi